### ISSUE TITLE
Multiple sequences per sample

### ISSUE THREAD

**Issue by samhunter** [ucdavis-bioinformatics/NeuroMabSeq#1]
Occasionally a single sample will contain multiple VH or VL sequences. These need to be supported from read summarization through to database and web page presentation. 

Some type of filter or intelligent strategy needs to be developed for identifying real multi-sequence samples (and differentiating from noisy amplicons).
Data interchange formats should be developed with to support multiple sequences per sample (possibly 2 files, one defining samples, the second defining sequences).
Database will need a 1:many relationship between CloneID and sequences.

**Comment by keithgmitchell** [comment]
@samhunter I think we have this issue mostly resolved right?

**Comment by samhunter** [comment]
Yes, I think this is pretty much resolved.
