### ISSUE TITLE
Multiple revision for detail view

### ISSUE THREAD

**Issue by samhunter** [ucdavis-bioinformatics/NeuroMabSeq#15]
A number of suggestions were made regarding presentation of the data:

1) Modify the layout so that the sequence is presented the full with of the page.

2) Add a new row for the translated Amino Acid sequence (coming soon). This might also need a strategy for displaying the AA numbering prediction from ANARCI.

3) Remove the "SMART Index" column (keep in database but don't display on page).

4) Remove the "Plate" column (keep in database but don't display on page).

5) Remove the analytics portion at the bottom or make it hidden and fold-out with a button click.

6) Remove "Percent Support" and "ASV Count" columns. Instead we need a way to indicate if the sequence is A) poorly supported (< 50 reads support it), and B) duplicated on the plate.

**Comment by msettles** [comment]
Keith, all these updates complete

**Comment by keithgmitchell** [comment]
Yes all of these are done except except how we want to indicate poor support or duplications. I think mostly the poorly supported. Waiting for AA data as well Sam is working with as part of his pipeline
