### ISSUE TITLE
Domain heading needs additional info

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#18]
Hi all,
I am of the opinion that the heading "Domain" as related to the amino acid sequences needs a key.

I suggest something like:

For light chains:
Domain: ANARCI prediction of IMTG amino acids 1-127

For heavy chains:
Domain: ANARCI prediction of IMTG amino acids 1-128

**Comment by keithgmitchell** [comment]
Done. We can go over how it all looks tomorrow as I also added a more formal domain layout that we will plan to color as well which we can discuss

**Comment by JimTrimmer** [comment]
Thanks Keith,
These changes look great.  I submitted a few other minor things in a new issue, mostly related to the new colorful section of the sequence pages.
Jim
