### ISSUE TITLE
Add "Return to Sequence Database" button to each sequence page

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#19]
Hi Keith and Sam,
![Example](https://user-images.githubusercontent.com/61327725/79257146-11354f80-7e3e-11ea-9a9c-581b37f086ed.jpg)

I realized that it is not straightforward to go from looking at specific sequences to getting back to the search page.  We need a "Return to Sequence Database"  button on the individual sequence pages.  About the same size as the one on the home page, and somewhere obvious perhaps in the upper right?  I attach a mock up of one possibility.

Jim

**Comment by keithgmitchell** [comment]
For now i have added this the way you have mentioned. Might be some cleaner options in the future we can continue to think about though
