### ISSUE TITLE
Organize entries

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#20]
Hi Keith and Sam,
I have a few suggestions as to the organization of entries:

1) very minor, remove "positive control" from N29/29. This is for internal; use and will confuse end users.
2) have the mAb IDs in the selection box listed in the same order as the archive itself, which is alphanumeric
3) this is the big one. We need to designate each entry into a category.  We will use something akin to how we prioritized these for sequencing, starting with the most important/well known/widely used subclones = Category 1, and going  down from there to Category 5 to relatively uncharacterized parents.  I asked our team to designate a category for each to add to the submission sheets.  We will also need a key and a dropdown menu, similar to and to the right of the one for the mAb IDs, that will allow users to filter the mAbs they see to the ones in that category.   Quite a few of the categories will have <500 entries.  The last one will be the largest but also the last sequenced.

**Comment by keithgmitchell** [comment]
Part 1 and 2 are done. 
Part 3 will need to be discussed tomorrow.

**Comment by samhunter** [comment]
I'm going to close this and move the category part to a new issue.

**Comment by JimTrimmer** [comment]
Hi Sam,
Got it, thanks.
Jim
