### ISSUE TITLE
A few additional minor issues

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#21]
1) Home page:  
change "Total Entries in Database" to "Total MAb Sequence Entries in Database"

2) Individual sequence pages

change "Domain: ANARCI prediction of IMTG amino acids 1-128"  to "ANARCI prediction of IMGT amino acids 1-128"
change "Domain: ANARCI prediction of IMTG amino acids 1-127" to "ANARCI prediction of IMGT amino acids 1-127"
change "Coloring Scheme for IMGT Domain"  to "IMGT amino acid positions"

**Comment by keithgmitchell** [comment]
Ok these should be done. But would you prefer that where i have "Mab ID " I change it to "MAb ID"

**Comment by JimTrimmer** [comment]
Hi Keith,
Sure. Thanks.
Jim

**Comment by JimTrimmer** [comment]
actually, better to have these as mAb
