### ISSUE TITLE
Support mAb_category on the web page

### ISSUE THREAD

**Issue by samhunter** [ucdavis-bioinformatics/NeuroMabSeq#23]
The following can only be implemented once we have category information in the sample sheets.

1) On the new_query page, add a dropdown or selection box indicating Category 1-5. Label it something like "mAb Category".

2) Include a very brief description of category 1-5 in the dropdown, add a key describing what the "mAb Category" means (e.g. 1 - High priority  somewhere (maybe a popup when the user mouses over the "mAb Category" title text?).

**Comment by samhunter** [comment]
Note:
Category 1 = most important/well known/widely used subclones
Category 5 = relatively uncharacterized parents

**Comment by keithgmitchell** [comment]
Need to add more categories but shoud be done now
