### ISSUE TITLE
Banner heading

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#28]
In looking at the website just now I concluded that the NeuroMabSeq "branding" is not sufficiently obvious.  I was think we need something in the header of every page.  I attach one idea.  Of course it would be nice to have a logo analogous to the one I created for the NeuroMab website, but for now some prominent text would suffice.  I realized this as I am giving a webinar in a week or so and wanted to show a screen grab of a sequence entry page, and it struck me that it was not very obvious where the page I was showing is from.  I am open to other ideas, instead of or in addition to the text in the banner.

![Banner heading](https://user-images.githubusercontent.com/61327725/82705617-cec91480-9c2c-11ea-8afc-80c9516c47cf.jpg)

**Comment by keithgmitchell** [comment]
should be done 
![image](https://user-images.githubusercontent.com/36057349/83310736-db67e280-a1c1-11ea-9a90-3447d0e3549b.png)
