### ISSUE TITLE
New category names

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#32]
1 | NeuroMab mAbs
2 | Non-NeuroMab mAbs
2 | NeuroMabs: alternate mAb subclones
4 | Lead oligoclonal Abs
5 | Other oligoclonal Abs
6 | Recombinant mAbs
7 | NeuroMab mAbs: commercially sequenced

**Comment by keithgmitchell** [comment]
Shoudl be taken care of
