### ISSUE TITLE
add two more rows to table on home page

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#37]
Hi Keith,
I wanted to remind you of the goal to add two more rows to the table on the home page, one for monoclonal samples and one for oligoclonal samples.  I did searches for each category, and came up with these numbers:

mAbs: 3597
oligoclonal Abs: 1502

The 9763 heavy chain and 7202 light chain sequences then need to be separated into those groups.
Jim

**Comment by keithgmitchell** [comment]
I believe this is done. Sorry just cleaning up some issues. Feel free to reopen if not.
