### ISSUE TITLE
home page modifications

### ISSUE THREAD

**Issue by JimTrimmer** [ucdavis-bioinformatics/NeuroMabSeq#8]
![NeuroMabSeq](https://user-images.githubusercontent.com/61327725/77206225-b107f380-6ab3-11ea-8b08-ea189060b84c.jpg)

**Comment by keithgmitchell** [comment]
![image](https://user-images.githubusercontent.com/36057349/77258620-fc97da00-6c38-11ea-9d33-4e91eb884a39.png)
